title: This is the site title

scripts:
# Anchor js is optional
  # - src: /assets/js/vendor/anchor.min.js
  #   async: true
# Main js - setting up anchor js
  # - src: /assets/js/main.js
  #   async: true
