title: SCINet Scientific Computing Initiative
description: SCINet is an initiative to provide access to high performance computing, networking and training

# GitHub information
# This is used for adding an edit this page link to the footer
github:
  organization: USDA-ARS-GBRU
  repository: scinet-site
  default_branch: master

baseurl: "/scinet-site"

# Configure a separator for post excerpts
excerpt_separator: "<!--end-excerpt-->"

# Configuration for setting the site width to 100%
# To enable, uncomment the following line
# site_width: wide

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-27627304-1


# Configuration for DAP, add your agency ID here:
dap_agency: USDA

# Uncomment to enable AnchorJS functionality on docs layout.
# See https://github.com/bryanbraun/anchorjs for more information.
# anchor_js_targets: [h1, h2, h3, h4, h5, h6]

# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.

# search_site_handle: searchgov-site-handle

# Configuration for projects and team collections
# See https://jekyllrb.com/docs/collections/ for more information about collections.
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  workshops:
    output: true
    permalink: /:collection/:path/
  team:
    people: true
    permalink: /:collection/:path/
    sort_by: page-position
  tutorials:
    output: true
    permalink: /:collection/:path/
#  announcements:
#    output: true
#    permalink: /:collection/:path/
#  stories:
#    output: true
#    permalink: /:collection/:path/

# Compress Sass
sass:
  style: compressed

# Add code blocks to text
highlighter: rouge

plugins:
  - jekyll-last-modified-at
