colors:
  primary: '#0071bc'
  primary-darker: '#205493'
  primary-darkest: '#112e51'
  primary-alt: '#02bfe7'
  primary-alt-dark: '#00a6d2'
  primary-alt-darkest: '#046b99'
  primary-alt-light: '#9bdaf1'
  primary-alt-lightest: '#e1f3f8'
  secondary: '#e31c3d'
  secondary-dark: '#cd2026'
  secondary-darkest: '#981b1e'
  secondary-light: '#e59393'
  secondary-lightest: '#f9dede'
  base: '#212121'
  focus: '#aeb0b5'
  visited: '#4c2c92'

fonts:
  sans: 'Source Sans Pro'
  serif: 'Merriweather'
  normal: 400
  bold: 700

images:
  graphic: '/assets/uswds/img/circle-124.png'
  hero: '/assets/uswds/img/hero.png'
